---
title: "BMI of Students in Scotland Throughout the School Year"
author: "Riley A. Moffat"
output: github_document
---

## Summary

This presentation is on the BMI of students in Scotland throughout the school year based on sex. My questions were, “As the school year time goes by, is there a greater change in the BMIs of the students? And what is the percentage of each sex for each BMI risk?” I have glimpsed at the data and found that it had 516 rows and 10 columns. The variables are `_id`, School Year, HBR, Sex, ValidReviews, EpiUnderweight, EpiHealthyweight, EpiOverweight, EpiObese, and EpiOverweightAndObese. The weight variables EpiUnderweight, EpiHealthyweight, EpiOverweight, EpiObese, and EpiOverweightAndObese are used for the weights of each student. I played around with combining the weight variables into one so I could possibly use it, but as I pasted them into one variable, it came into a group of weights. I also played with mutating them together, but the result was an error. I feel it best to not combine the data with the way I must present it. I have first created scatterplots for my first visualizations to show my data and the relationship between the school years and the weights of the students based on sex. You can see that not many females are underweight as much as the boys. But I thought that this would be too boring and confusing, so I used boxplots like they were histograms, except they have both the x and the y variables in them. For the boxplot labeled “Underweight Students Through the School Year by Sex,” I found there were more underweight boys than girls. The x-variable labeled as “School Year” is messy, but I found that there is an increase of underweight students and then a decrease of them before halfway. For the boxplot labeled “Healthy weight Students Through the School Year by Sex,” there is a similar amount of healthy weight girls as there are healthy weight boys. First, there are more healthy weight girls than boys, then more healthy weight boys than girls. The amount of healthy weight students increased then, at around two-thirds of the plot, decreased and then increased. For the boxplot labeled “Overweight Students Through the School Year by Sex,” it seems like there are more overweight students overall than the lighter students. First, there are more overweight boys than girls, then the trend fluctuates. First, the amount of overweight students increased, then decreased at around two-thirds of the plot. The boxplot labeled “Obese Students Through the School Year by Sex” proves that there are less obese students than there are overweight and healthy weight students, proving that the students in Scotland are more overweight. First, the number of obese students in Scotland increase, then it decreases. Therefore, there are more overweight students in Scotland than there are lightweight, healthy weight, and obese students, and not many students are lightweight because the plot for that shows that less students are lightweight, especially the girls.

```{r load-data, echo = FALSE}
library(readxl)
bmi <- read_excel("data/bmi.xlsx")

```

## Presentation

My presentation can be found [here](https://www.opendata.nhs.scot/dataset/primary-1-body-mass-index-bmi-statistics/resource/670e4c0d-ab1e-4006-a0f2-6bc3fad8dbe3).

## Data 

Public Health Scotland, 2024, "Epidemiological BMI by Gender at Health Board Level", Primary 1 by gender at health board level, Public Health Scotland

## References

Public Health Scotland, https://www.opendata.nhs.scot/dataset/primary-1-body-mass-index-bmi-statistics/resource/670e4c0d-ab1e-4006-a0f2-6bc3fad8dbe3

